version: '3.7'

services:
    git_repo_sync-api:
        build:
            context: .
            dockerfile: dev.dockerfile
        container_name: git_repo_sync-api
        volumes:
            - .:/src/git_repo_sync/
            - ~/Workspace/Data:/data
        ports:
            - "5000:5000"
        env_file:
            - env/.env.dev
